SELECT 'ALTER TABLE TABLE_OWNER.' || TABLE_NAME || ' DROP (' || COLUMNS || ');' SENTENCIA FROM (
    SELECT
        TABLE_NAME,
        LISTAGG(COLUMN_NAME, ', ') WITHIN GROUP (ORDER BY COLUMN_NAME) "COLUMNS"
    FROM
        ALL_TAB_COLUMNS
    WHERE
        COLUMN_NAME LIKE '%TABLE_FILTER%' AND OWNER = 'TABLE_OWNER'
    GROUP BY
        TABLE_NAME
    ORDER BY
        TABLE_NAME
);
