SELECT 
    LPAD (' ', (LEVEL - 1) * 2, ' ') || NVL (S.USERNAME, '(oracle)') AS USERNAME,
    S.SID,
    S.serial#,
    TO_CHAR (S.LOGON_TIME, 'DD-MON-YYYY HH24:MI:SS') AS LOGON_TIME
FROM 
    V$SESSION S
CONNECT BY PRIOR S.SID = S.BLOCKING_SESSION
START WITH S.BLOCKING_SESSION IS NULL;

ALTER SYSTEM KILL SESSION 'SID,SERIAL#';
