SELECT
    C2.CONSTRAINT_NAME CONSTRAINT, C2.TABLE_NAME CONSTRAINT_TABLE,
    C1.CONSTRAINT_NAME REFERRED_PK, C1.TABLE_NAME REFERRED_TABLE
FROM
ALL_CONSTRAINTs C1,
ALL_CONSTRAINTs C2
WHERE
    C1.owner = 'C1_OWNER' AND
    C2.owner = 'C2_OWNER' AND
    C1.constraint_Type = 'R' AND
    C1.R_CONSTRAINT_NAME = C2.CONSTRAINT_NAME
    AND c2.TABLE_NAME = 'TABLE_NAME'
ORDER BY C1.TABLE_NAME, C2.TABLE_NAME
